### ISSUE TITLE
Checklist for release of `v2.0.0`

### ISSUE THREAD

**Issue by UltraInstinct05** [Sublime-Instincts/BetterJinja#13]
### Description of your enhancement/feature request proposal.

This is basically an issue to track various stuff for the `v2.0.0` release. I had initially planned to do a `v1.2.0` with some syntax cleanups, but let's just do a direct `v2.0.0`.

- [x] Split the syntax into a core `Jinja` and then create `HTML (Jinja)`, `CSS (Jinja)` & `JavaScript (Jinja)` variants of it. This will resolve #7 and also supersede #10 without the need for `yaml-macros`.
- [ ] Create a `YAML (Jinja)` variant. This will be the only additional variant that will ship with `v2.0.0`. More can be added as & when users request it.
- [ ] Indentation tests
- [ ] Make the test suite more robust.

Other things that I might add in the future.
